name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------
      # SERVER
      # -------------------
      - name: Install server deps
        run: |
          cd server
          npm install


      - name: Build server
        run: |
          cd server
          npm run build

      # -------------------
      # CLIENT
      # -------------------
      - name: Install client deps
        run: |
          cd client
          npm install

      - name: Build client
        run: |
          cd client
          npm run build